// Generated by slidev-theme-kotlin from slides.md, slide 10 "Ignoring a return value is a warning".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide10;

import presentation.support.*;
import org.jetbrains.annotations.CheckReturnValue;

@CheckReturnValue
public class Money {
  private final long cents;

  public Money(long cents) { this.cents = cents; }

  public Money plus(Money other) { return new Money(cents + other.cents); }
}
