// Generated by slidev-theme-kotlin from slides.md, slide 1 "Kotlin at Devoxx Belgium 2026".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide1;

import presentation.support.*;

public class Register {
  Money total = Money.zero();
}
