// Generated by slidev-theme-kotlin from slides.md, slide 12 "Kotlin compiles for Java 26".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide12;

import presentation.support.*;

public sealed interface Shape permits Circle, Square {}
record Circle(double radius) implements Shape {}
record Square(double side) implements Shape {}
