// Generated by slidev-theme-kotlin from slides.md, slide 11 "Nullability is part of the type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide11;

import presentation.support.*;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
public class Users {
  public static @Nullable String nickname(String id) { return null; }
}
