// Generated by slidev-theme-kotlin from slides.md, slide 4 "A companion extension needs no companion".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide4

import presentation.support.*
import java.time.LocalDate

companion fun LocalDate.epoch() = LocalDate.ofEpochDay(0)

suspend fun main() {
    println(LocalDate.epoch())
}
