// Generated by slidev-theme-kotlin from slides.md, slide 5 "Square brackets build a collection".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide5

import presentation.support.*

val names = ["Ada", "Linus", "Grace"]

val ages: Set<Int> = [36, 17, 28]

fun sum(numbers: Iterable<Int>): Int = numbers.sum()

val six = sum([1, 2, 3])
