// Generated by slidev-theme-kotlin from slides.md, slide 6 "A literal needs an `of()`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide6

import presentation.support.*

@JvmInline
value class Team(private val members: List<Member>) {
  companion object {
    operator fun of(vararg members: Member) = Team(members.toList())
  }
}

val team: Team = [Member("Ada", 36), Member("Linus", 17)]

suspend fun main() {
  println(team)
}
