// Generated by slidev-theme-kotlin from slides.md, slide 6 "`context` supplies a context without a receiver".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide6

import presentation.support.*

class Logger(val tag: String) {
  fun log(message: String) = println("[$tag] $message")
}

context(logger: Logger)
fun greet(name: String) = logger.log("hello, $name")

fun main() = context(Logger("APP")) {
  greet("Grace")
}
