// Generated by slidev-theme-kotlin from slides.md, slide 7 "An explicit backing field replaces the underscore".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide7

import presentation.support.*

class Cart {
  val items: List<String>
    field = mutableListOf()

  fun add(item: String) {
    items.add(item)
  }
}
