// Generated by slidev-theme-kotlin from slides.md, slide 7 "Destructuring matches by name, not position".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide7

import presentation.support.*

data class Person(val name: String, val age: Int)

val person = Person("Ada", 36)

suspend fun main() {
    val (age, name) = person

    println("$name is $age")
}
