// Generated by slidev-theme-kotlin from slides.md, slide 10 "Ignoring a return value is a warning".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide10

import presentation.support.*

val price = Money(1000)

suspend fun main() {
    price.plus(Money(250))
}
