// Generated by slidev-theme-kotlin from slides.md, slide 12 "Kotlin compiles for Java 26".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide12

import presentation.support.*

fun area(shape: Shape): Double = when (shape) {
  is Circle -> Math.PI * shape.radius * shape.radius
  is Square -> shape.side * shape.side
}
