// Generated by slidev-theme-kotlin from slides.md, slide 13 "`when` compiles to `invokedynamic`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.slides.slide13

import presentation.support.*

sealed interface Shape

data class Circle(val radius: Double) : Shape

data class Square(val side: Double) : Shape

fun area(shape: Shape): Double = when (shape) {
  is Circle -> Math.PI * shape.radius * shape.radius
  is Square -> shape.side * shape.side
}
